# RF code mappings
RF_CODE_MAPPINGS:
  7619720: "Main Door"
  2840472: "Kitchen Door"
  4063832: "Drawing Rm Door"
  4956704: "JK Room Motion"

IR_TRANSMITTER:
  SERVER_PORT: 8094

RF_TRANSMITTER:
  SERVER_PORT: 8090
  CODE_SEND_BINARY_PATH: "/home/pi/test/433Utils/RPi_utils/codesend"

RF_RECEIVER:
  SERVER_PORT: 8093

RFID_LISTENER:
  # RFID Tags
  SECURITY_LOCK_UNLOCK_ID: "118983175"
  OUTDOOR_LIGHTS_TOGGLE_ID: "163200171117"

  # configs
  SLEEP_BETWEEN_READS_IN_MS: 1

LCD_SCREEN:
  SERVER_PORT: 8091

BUZZER:
  SERVER_PORT: 8092

COMMON:
  # RF Codes
  SECURITY_UNLOCK_CODE: "1488996 1 450"
  SECURITY_LOCK_CODE: "1488994 1 450"

  LIGHT_JAVED_ROOM_ON: "16733443 1 468"
  LIGHT_JAVED_ROOM_FAN_ON: "16733455 1 468"
  LIGHT_JAVED_INDOOR_DOWNSTAIRS_ON: "16733644 1 468"
  LIGHT_JAVED_INDOOR_UPSTAIRS_ON: "16733647 1 468"
  LIGHT_KITCHEN_ON: "16733635 1 468"
  LIGHT_WATER_MOTOR_ON: "16733632 1 468"
  LIGHT_GEEZER_ON: "16733503 1 468"
  LIGHT_PARKING_ON: "16733491 1 468"
  LIGHT_GATE_ON: "16733488 1 468"
  LIGHT_GARDEN_ON: "16733500 1 468"

  LIGHT_JAVED_ROOM_OFF: "16742659 1 468"
  LIGHT_JAVED_ROOM_FAN_OFF: "16742671 1 468"
  LIGHT_JAVED_INDOOR_DOWNSTAIRS_OFF: "16742862 1 468"
  LIGHT_JAVED_INDOOR_UPSTAIRS_OFF: "16742865 1 468"
  LIGHT_KITCHEN_OFF: "16742851 1 468"
  LIGHT_WATER_MOTOR_OFF: "16742848 1 468"
  LIGHT_GEEZER_OFF: "16742719 1 468"
  LIGHT_PARKING_OFF: "16742707 1 468"
  LIGHT_GATE_OFF: "16742704 1 468"
  LIGHT_GARDEN_OFF: "16742716 1 468"

  # [25/02 10:09:20AM] - Received[25] on PIN 2. Code: 15080663. Delay: 312
  # [25/02 10:09:27AM] - Received[26] on PIN 2. Code: 15080671. Delay: 312
  SOCKET_WATER_MOTOR_ON: "15080671 1 312"
  SOCKET_WATER_MOTOR_OFF: "15080663 1 312"

SCHEDULER:
  SERVER_PORT: 8095
  TIME_BEFORE_SUNSET: 20
  TIME_BEFORE_SUNRISE: -10
  SECURITY_UNLOCK_CODE: "1488996 1 450"

# test
MOBILE:
  IP_ADDRESS: "192.168.1.198"
  ARP_SCAN_COMMAND: "arp-scan -l | grep 00:34:da:55:72:9e"