# RF code mappings
RF_CODE_MAPPINGS:
  7619720: "Main Door"
  2840472: "Kitchen Door"
  4063832: "Drawing Rm Door"
  4956704: "JK Room Motion"

IR_TRANSMITTER:
  SERVER_PORT: 8094

RF_TRANSMITTER:
  SERVER_PORT: 8090
  CODE_SEND_BINARY_PATH: "/home/pi/test/433Utils/RPi_utils/codesend"

RF_RECEIVER:
  SERVER_PORT: 8093

RFID_LISTENER:
  # RFID Tags
  SECURITY_LOCK_UNLOCK_ID: "118983175"
  OUTDOOR_LIGHTS_TOGGLE_ID: "163200171117"

  # configs
  SLEEP_BETWEEN_READS_IN_MS: 1

LCD_SCREEN:
  SERVER_PORT: 8091

BUZZER:
  SERVER_PORT: 8092

COMMON:
  # RF Codes
  SECURITY_UNLOCK_CODE: "1488996 1 450"
  SECURITY_LOCK_CODE: "1488994 1 450"
  LIGHT_JAVED_ROOM: "5731647 1 235"
  LIGHT_JAVED_ROOM_FAN: "5731824 1 235"
  LIGHT_WATER_MOTOR: "5731779 1 235"
  LIGHT_GEEZER: "5731644 1 235"
  LIGHT_MAIN_DOOR: "5731599 1 235"
  LIGHT_PARKING: "5731788 1 235"
  LIGHT_GATE: "5731632 1 235"
  LIGHT_GARDEN: "5731596 1 235"

  # [25/02 10:09:20AM] - Received[25] on PIN 2. Code: 15080663. Delay: 312
  # [25/02 10:09:27AM] - Received[26] on PIN 2. Code: 15080671. Delay: 312
  SOCKET_WATER_MOTOR_ON: "15080671 1 312"
  SOCKET_WATER_MOTOR_OFF: "15080663 1 312"

SCHEDULER:
  TIME_BEFORE_SUNSET: 10
  TIME_BEFORE_SUNRISE: 10

# test
MOBILE:
  IP_ADDRESS: "192.168.1.198"
  ARP_SCAN_COMMAND: "arp-scan -l | grep 00:34:da:55:72:9e"